version: '3'
services:
    app:
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
        container_name: app
        restart: unless-stopped
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        working_dir: /var/www/mammology
        volumes:
            - '.:/var/www/mammology'
        depends_on:
            - database
        networks:
            - my_network

    python:
        restart: unless-stopped
        container_name: python
        build:
            context: .
            dockerfile: ./docker/python/Dockerfile
        ports:
            - "5000:5000"
        working_dir: /python
        volumes:
            - './AI:/python'
        networks:
            - my_network
        command: [ "python", "app.py", "gunicorn app:app --workers 4 --threads 2"]

    nginx:
        container_name: server
        image: 'nginx:alpine'
        restart: unless-stopped
        ports:
            - '80:80'
        volumes:
            - '.:/var/www/mammology'
            - './docker/nginx/conf.d/:/etc/nginx/conf.d/'
        depends_on:
            - app
        networks:
            - my_network

    database:
        container_name: db
        image: 'postgres:14.5'
        environment:
            - 'POSTGRES_DB=${DB_DATABASE}'
            - 'POSTGRES_USER=${DB_USERNAME}'
            - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
        ports:
            - '${DB_PORT}:5432'
        volumes:
            - 'postgresql:/var/lib/postgresql/data/'

networks:
    my_network:
        driver: bridge
        name: my_network
volumes:
    postgresql:
        driver: local

